version: "3"

services:
  tests:
    build: 
      context: ..
      dockerfile: dev/dockerfiles/tests-dotnet.dockerfile
  
  tests-ui:
    build: 
      context: ..
      dockerfile: dev/dockerfiles/tests-ui.dockerfile