version: "3"

services:
  traefik:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: traefik
  
  timescale:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: timescale

  proxy-core:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: proxy-core
    build: 
      context: ..
      dockerfile: dev/dockerfiles/dotnet.dockerfile
      args:
        PROJECT: dev/helpers/Foundation.Template.Proxy
    environment:
      DOTNET_ENVIRONMENT: Development
      DOTNET_URLS: http://+:80

  proxy-admin:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: proxy-admin
    build: 
      context: ..
      dockerfile: dev/dockerfiles/dotnet.dockerfile
      args:
        PROJECT: dev/helpers/Foundation.Template.Proxy
    environment:
      DOTNET_ENVIRONMENT: Development
      DOTNET_URLS: http://+:80

  core:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: core
    build: 
      context: ..
      dockerfile: dev/dockerfiles/dotnet-fake-nuget.dockerfile
      args:
        PROJECT: src/template/src/app/core/XXXXX.Core.API
        TEMPLATE_VERSION: 9.9.9
  
  admin:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: admin
    build: 
      context: ..
      dockerfile: dev/dockerfiles/dotnet-fake-nuget.dockerfile
      args:
        PROJECT: src/template/src/app/admin/XXXXX.Admin.API
        TEMPLATE_VERSION: 9.9.9
    
  gateway:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: gateway
    build: 
      context: ..
      dockerfile: dev/dockerfiles/dotnet-fake-nuget.dockerfile
      args:
        PROJECT: src/template/src/app/gateway/XXXXX.Gateway.API
        TEMPLATE_VERSION: 9.9.9
  
  ui:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: ui
    build: 
      context: ..
      dockerfile: dev/dockerfiles/vue-fake-npm.dockerfile
    environment:
      PROJECT: xxxxx-core-ui
    volumes:
      - ../src/app/core/Foundation.Template.Core-UI:/app/lib/Foundation.Template.Core-UI:delegated
      - ../src/shared/Foundation.Template.Shared-UI:/app/lib/Foundation.Template.Shared-UI:delegated
  
  admin-ui:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: admin-ui
    build: 
      context: ..
      dockerfile: dev/dockerfiles/vue-fake-npm.dockerfile
    environment:
      PROJECT: xxxxx-admin-ui
    volumes:
      - ../src/app/core/Foundation.Template.Admin-UI:/app/lib/Foundation.Template.Admin-UI:delegated
      - ../src/shared/Foundation.Template.Shared-UI:/app/lib/Foundation.Template.Shared-UI:delegated
  
  migrations:
    extends:
      file: ../src/template/dev/docker-compose.yml
      service: migrations
    build: 
      context: ..
      dockerfile: dev/dockerfiles/dotnet-fake-nuget.dockerfile
      args:
        PROJECT: src/template/src/app/core/XXXXX.Core.API
        TEMPLATE_VERSION: 9.9.9

networks:
  bones:

volumes:
  data-postgres: