name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - "src/app/Foundation.Template.Admin"
          - "src/app/Foundation.Template.Gateway"
          - "src/app/Foundation.Template.Shell"
          - "context/Foundation.Template.Context"
          - "context/Foundation.Template.Fixtures"
          - "shared/Foundation.Template.CrossCutting"
          - "shared/Foundation.Template.Domain"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Build
        run: |
          cd src/app/${{matrix.folder}}
          dotnet build --configuration Release
