name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["Foundation.Template.Admin", "Foundation.Template.Gateway", "Foundation.Template.Shell"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Build
        run: |
          cd src/app/${{matrix.folder}}
          dotnet build --configuration Release
