name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - "src/app/Foundation.Extension.Admin"
          - "src/app/Foundation.Extension.Gateway"
          - "src/app/Foundation.Extension.Core"
          - "src/context/Foundation.Extension.Context"
          - "src/context/Foundation.Extension.Fixtures"
          - "src/shared/Foundation.Extension.CrossCutting"
          - "src/shared/Foundation.Extension.Domain"
          - "dev/helpers/Foundation.Extension.Proxy"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Build
        run: |
          cd ${{matrix.folder}}
          dotnet build --configuration Release
