name: Publish Package to NPM

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
  
    steps:
      # Checking out repository
      - uses: actions/checkout@v4
      
      # Setting .npmrc file up to publish to npm
      - name: Setting things up 🔧
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dative-gpi'

      # Publishing with tag name as version
      - name: Publishing to npm 🚀
        run: |
          lerna publish ${{ github.ref_name }} --exact --no-git-tag-version --yes --no-private --force-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}